tools:
  - class_name: "verl.tools.cxr1k_tool.Cxr1kTool"
    config: 
      type: native
    tool_schema:
      type: "function"
      function:
        name: "crop_cxr1k_image"
        description: "A tool for cropping a more detailed image for CXR1K dataset."
        parameters:
          type: "object"
          properties:
            answer:
              type: "string"
              description: "The model's answer to cropping the CXR1K image, must be a string in the format 'x1,y1,x2,y2' where (x1,y1) is the top-left corner and (x2,y2) is the bottom-right corner of the crop area."
          required: ["answer"]